name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Grid
        uses: Platane/snk@v3
        with:
          github_user_name: chowdhoury
          outputs: |
            dist/grid.svg

      - name: Push the generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist"
